name: blip_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - brotli-python=1.0.9
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.14.6
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - jinja2=3.1.5
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.2.1
  - openjpeg=2.5.2
  - openssl=3.4.1
  - pillow=11.1.0
  - pycparser=2.22
  - pysocks=1.7.1
  - python_abi=3.9
  - pytorch=2.5.1
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==1.4.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - blis==1.2.0
      - catalogue==2.0.10
      - click==8.1.8
      - cloudpathlib==0.20.0
      - confection==0.1.5
      - cymem==2.0.11
      - datasets==3.3.2
      - dill==0.3.8
      - en-core-web-sm==3.8.0
      - filelock==3.17.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - huggingface-hub==0.28.1
      - joblib==1.4.2
      - langcodes==3.5.0
      - language-data==1.3.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.12
      - nltk==3.9.1
      - numpy==2.0.2
      - packaging==24.2
      - pandas==2.2.3
      - preshed==3.0.9
      - propcache==0.3.0
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - python-dateutil==2.9.0.post0
